# codemagic.yaml

workflows:
  react_native_build:
    name: React Native Build
    scripts:
      # Define your build commands here.
      # For React Native, it's typically "npm install" and "npm run build".
      # Adjust these commands based on your project setup.
      - name: Install Dependencies
        script: npm install
      - name: Build App
        script: npm run build